kind: Service
apiVersion: v1
metadata:
  name: matchmove
spec:
  type: NodePort
  selector:
    app: matchmove
  ports:
  - port: 3000
    name: matchmove
    targetPort: 3000
    protocol: TCP
    nodePort: 31158